Rails.application.routes.draw do

  # Generated by jumaccount_generator 1.0.0 Start (vor resources :profiles!)
  get 'users/profiles/edit'   => 'profiles#useredit', :as => 'edit_user_profile'
  get 'users/profiles/quit'   => 'profiles#quit', :as => 'quit_user_profile'

  get   'users/:user_id/rights' => 'rights#userindex',  :as => 'user_rights'
  post  'users/:user_id/rights' => 'rights#usercreate',  :as => 'create_user_right'
  get   'users/:user_id/rights/new' => 'rights#usernew',  :as => 'new_user_right'
  get   'users/:user_id/rights/:id/edit' => 'rights#useredit',  :as => 'edit_user_right'
  get   'users/:user_id/rights/:id' => 'rights#usershow',  :as => 'user_right'
  patch 'users/:user_id/rights/:id' => 'rights#userupdate'
  put   'users/:user_id/rights/:id' => 'rights#userupdate'
  delete 'users/:user_id/rights/:id' => 'rights#userdestroy'
  get   'users/:user_id/rights/:id/choose' => 'rights#userchoose',  :as => 'choose_user_right'
  # Generated by jumaccount_generator 1.0.0 Ende

  resources :profiles

  resources :rights

  resources :teams

  resources :companies

  resources :discs

  root to: 'visitors#index'
  devise_for :users
  resources :users
  
end
