class Disc < ActiveRecord::Base
  # Generated by jumaccount_generator 1.0.0 Start
  belongs_to :user
  belongs_to :company
  belongs_to :team

  validates  :user_id, presence: true
  validates  :company_id, presence: true
  validates  :team_id, presence: true

  def set_admission(right)
    self.user_id    = right.user_id
    self.company_id = right.company_id
    self.team_id    = right.team_id
    return self
  end
  # End of generator insertion

  after_initialize :init, :if => :new_record?
  
  def init
    if self.new_record?
      self.feld1 ||= ""
      self.feld1 ||= ""
      self.tracks ||= 0
    end
  end

end
